_display = uiNamespace getVariable ["BIS_WL_purchaseMenuDisplay", displayNull];
_purchase_category = _display displayCtrl 100;
_purchase_items = _display displayCtrl 101;
_purchase_pic = _display displayCtrl 102;
_purchase_info = _display displayCtrl 103;
_purchase_income = _display displayCtrl 104;
_purchase_info_asset = _display displayCtrl 105;
_purchase_title_cost = _display displayCtrl 106;
_purchase_request = _display displayCtrl 107;
_purchase_title_queue = _display displayCtrl 108;
_purchase_queue = _display displayCtrl 109;
_purchase_remove_item = _display displayCtrl 110;
_purchase_remove_all = _display displayCtrl 111;
_purchase_drop_sector = _display displayCtrl 112;
_purchase_drop_player = _display displayCtrl 113;
_purchase_title_drop = _display displayCtrl 114;
_curSel = (lbCurSel _purchase_items) max 0;
_assetDetails = (_purchase_items lbData _curSel) splitString "|";
_pic = _assetDetails # 3;
if (_pic == " ") then {_pic = ""};
_purchase_pic ctrlSetStructuredText parseText format ["<img image = '%1' size = '%2' align = 'center' shadow = '0'></img>", _pic, (7.693 call BIS_fnc_WLSubroutine_purchaseMenuGetUIScale)];
_id = _purchase_category lbValue lbCurSel _purchase_category;
_purchase_info_asset ctrlSetStructuredText parseText format ["<t align = 'center' size = '%2'>%1</t>", (((player getVariable "BIS_WL_purchasable") # _id) # (lbCurSel _purchase_items)) # 5, (0.85 call BIS_fnc_WLSubroutine_purchaseMenuGetUIScale)];
_cost = _purchase_items lbValue lbCurSel _purchase_items;
_requirements = (((player getVariable "BIS_WL_purchasable") # _id) # (lbCurSel _purchase_items)) # 2;
_purchase_title_cost ctrlSetStructuredText parseText format ["<t size = '%7' align = 'center' shadow = '0'>%1%8: %2 %3%4%5%6</t>", localize "STR_A3_WL_menu_cost", _cost, localize "STR_A3_WL_unit_cp", if ("A" in _requirements) then {", " + localize "STR_A3_WL_param32_title"} else {""}, if ("H" in _requirements) then {", " + localize "STR_A3_WL_module_service_helipad"} else {""}, if ("W" in _requirements) then {", " + localize "STR_A3_WL_param30_title"} else {""}, (1.25 call BIS_fnc_WLSubroutine_purchaseMenuGetUIScale), if (toLower language == "french") then {" "} else {""}];
call BIS_fnc_WLSubroutine_purchaseMenuRefresh;