// config.bin - 18:33:23 07/16/20, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class A3_Language_F_MP_Mark {
		author = "$STR_A3_Bohemia_Interactive";
		name = "Arma 3 Marksmen (Multiplayer) - Texts and Translations";
		url = "https://www.arma3.com";
		requiredAddons[] = {"A3_Data_F_Mark"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {};
	};
};

class CfgHints {
	class Multiplayer {
		class DynamicGroups {
			displayName = "$STR_A3_DynamicGroups1";
			description = "$STR_A3_DynamicGroups2";
			tip = "";
			image = "\A3\Ui_f\data\GUI\Cfg\Hints\Rifle_ca.paa";
			arguments[] = {{{"teamSwitch"}}};
			logicalOrder = 6;
		};
	};
	
	class Common {
		class Containers {
			class EndGameVirtualArsenal_sub {
				displayName = "$STR_A3_rscdisplaymain_buttonvirtualarsenal";
				description = "$STR_A3_EndGameVA2";
				tip = "";
				image = "\A3\Ui_f\data\GUI\Cfg\Hints\Switch_ca.paa";
				arguments[] = {};
			};
		};
	};
};
