class CfgGroups
{
	class Indep
	{
		name = $STR_A3_CfgGroups_West0;
		side = TGuerrila;
		class IND_C_F
		{
			name = $STR_A3_CfgGroups_West_BLU_F0;
			class Infantry
			{
				name = $STR_A3_CfgGroups_West_BLU_F_Infantry0;
				class EfT_I_Team01
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TGuerrila;
					faction = IND_F;
					class Unit0 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_4_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_5_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_7_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_7_F; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfT_I_Team02
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TGuerrila;
					faction = IND_F;
					class Unit0 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_4_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_5_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_5_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TGuerrila; vehicle = I_C_Soldier_Bandit_7_F; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfT_I_Team03
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TGuerrila;
					faction = IND_F;
					class Unit0 	{side = TGuerrila; vehicle = I_C_Soldier_Para_1_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TGuerrila; vehicle = I_C_Soldier_Para_4_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TGuerrila; vehicle = I_C_Soldier_Para_6_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TGuerrila; vehicle = I_C_Soldier_Para_7_F; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfT_I_Team04
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TGuerrila;
					faction = IND_F;
					class Unit0 	{side = TGuerrila; vehicle = I_C_Soldier_Para_1_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TGuerrila; vehicle = I_C_Soldier_Para_4_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TGuerrila; vehicle = I_C_Soldier_Para_5_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TGuerrila; vehicle = I_C_Soldier_Para_7_F; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfT_I_Team05
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TGuerrila;
					faction = IND_F;
					class Unit0 	{side = TGuerrila; vehicle = I_C_Soldier_Para_1_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TGuerrila; vehicle = I_C_Soldier_Para_4_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TGuerrila; vehicle = I_C_Soldier_Para_3_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TGuerrila; vehicle = I_C_Soldier_Para_7_F; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfT_I_Squad01
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TGuerrila;
					faction = IND_F;
					class Unit0 	{side = TGuerrila; vehicle = I_C_Soldier_Para_2_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TGuerrila; vehicle = I_C_Soldier_Para_3_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TGuerrila; vehicle = I_C_Soldier_Para_5_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TGuerrila; vehicle = I_C_Soldier_Para_4_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TGuerrila; vehicle = I_C_Soldier_Para_1_F; rank = "PRIVATE"; position[] = {-10,-10,0};};
					class Unit5 	{side = TGuerrila; vehicle = I_C_Soldier_Para_7_F; rank = "PRIVATE"; position[] = {15,-15,0};};
				};
				class EfT_I_Squad02
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TGuerrila;
					faction = IND_F;
					class Unit0 	{side = TGuerrila; vehicle = I_C_Soldier_Para_2_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TGuerrila; vehicle = I_C_Soldier_Para_6_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TGuerrila; vehicle = I_C_Soldier_Para_4_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TGuerrila; vehicle = I_C_Soldier_Para_5_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TGuerrila; vehicle = I_C_Soldier_Para_1_F; rank = "PRIVATE"; position[] = {-10,-10,0};};
					class Unit5 	{side = TGuerrila; vehicle = I_C_Soldier_Para_7_F; rank = "PRIVATE"; position[] = {15,-15,0};};
				};
			};
		};
	};
	class East
	{
		name = $STR_A3_CfgGroups_West0;
		side = TEast;
		class OPF_T_F
		{
			name = $STR_A3_CfgGroups_West_BLU_F0;
			class Infantry
			{

				class EfT_O_Team01
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TEast;
					faction = OPF_F;
					class Unit0 	{side = TEast; vehicle = O_T_Soldier_TL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TEast; vehicle = O_T_Soldier_AR_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TEast; vehicle = O_T_Soldier_LAT_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TEast; vehicle = O_T_Soldier_F; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
				class EfT_O_Team02
				{
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TEast;
					faction = OPF_F;
					class Unit0 	{side = TEast; vehicle = O_T_Soldier_GL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TEast; vehicle = O_T_Soldier_AR_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TEast; vehicle = O_T_Soldier_M_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TEast; vehicle = O_T_Soldier_F; rank = "PRIVATE"; position[] = {10,-10,0};};
				};
			};
		};
	};
};
