class CfgGroups {
	class West {
		name = $STR_A3_CfgGroups_West0;
		side = TWest;
		class BLU_F {
			name = $STR_A3_CfgGroups_West_BLU_F0;
			class Infantry {
				name = $STR_A3_CfgGroups_West_BLU_F_Infantry0;
				class EfM_W_Team01 {
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = BLU_F;
					class Unit0 	{side = TWest; vehicle = B_soldier_TL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = B_soldier_AR_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = B_soldier_M_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = B_soldier_LAT_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = B_soldier_AA_F; rank = "PRIVATE"; position[] = {10,-15,0};}; //NNS
				};
				
				class EfM_W_Team02 {
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = BLU_F;
					class Unit0 	{side = TWest; vehicle = B_soldier_TL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = B_heavyGunner_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = B_soldier_M_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = B_soldier_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = B_soldier_AA_F; rank = "PRIVATE"; position[] = {10,-15,0};}; //NNS
				};
				
				class EfM_W_Team03 {
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = BLU_F;
					class Unit0 	{side = TWest; vehicle = B_soldier_GL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = B_soldier_AR_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = B_sharpshooter_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = B_soldier_LAT_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = B_soldier_AA_F; rank = "PRIVATE"; position[] = {10,-15,0};}; //NNS
				};
				
				class EfM_W_Team04 {
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = BLU_F;
					class Unit0 	{side = TWest; vehicle = B_soldier_GL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = B_soldier_AR_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = B_soldier_M_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = B_soldier_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = B_soldier_AA_F; rank = "PRIVATE"; position[] = {10,-15,0};}; //NNS
				};
				
				class EfM_W_Squad01 {
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = BLU_F;
					class Unit0 	{side = TWest; vehicle = B_soldier_SL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = B_heavyGunner_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = B_soldier_LAT_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = B_soldier_GL_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = B_soldier_M_F; rank = "PRIVATE"; position[] = {-10,-10,0};};
					class Unit5 	{side = TWest; vehicle = B_soldier_F; rank = "PRIVATE"; position[] = {15,-15,0};};
					class Unit6 	{side = TWest; vehicle = B_soldier_AA_F; rank = "PRIVATE"; position[] = {15,-20,0};}; //NNS
				};
				
				class EfM_W_Squad02 {
					name = $STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0;
					side = TWest;
					faction = BLU_F;
					class Unit0 	{side = TWest; vehicle = B_soldier_SL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TWest; vehicle = B_soldier_AR_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TWest; vehicle = B_soldier_LAT_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TWest; vehicle = B_sharpshooter_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TWest; vehicle = B_medic_F; rank = "PRIVATE"; position[] = {-10,-10,0};};
					class Unit5 	{side = TWest; vehicle = B_soldier_F; rank = "PRIVATE"; position[] = {15,-15,0};};
					class Unit6 	{side = TWest; vehicle = B_soldier_AA_F; rank = "PRIVATE"; position[] = {15,-20,0};}; //NNS
				};
			};
		};
	};

	class East { //NNS
		name = $STR_A3_CfgGroups_East0;
		side = TEast;
		class OPF_G_F {
			name = $STR_A3_CfgGroups_East_OPF_G_F0;
			class Infantry {
				name = $STR_A3_CfgGroups_East_OPF_G_F_Infantry0;
				class EfM_E_Squad01 {
					name = $STR_A3_CfgGroups_East_OPF_G_F_Infantry_BUS_InfSquad0;
					side = TEast;
					faction = OPF_F;
					class Unit0 	{side = TEast; vehicle = O_G_Soldier_SL_F; rank = "CORPORAL"; position[] = {0,0,0};};
					class Unit1 	{side = TEast; vehicle = O_G_Soldier_AR_F; rank = "PRIVATE"; position[] = {5,-5,0};};
					class Unit2 	{side = TEast; vehicle = O_G_Soldier_LAT2_F; rank = "PRIVATE"; position[] = {-5,-5,0};};
					class Unit3 	{side = TEast; vehicle = O_G_Sharpshooter_F; rank = "PRIVATE"; position[] = {10,-10,0};};
					class Unit4 	{side = TEast; vehicle = O_G_Medic_F; rank = "PRIVATE"; position[] = {-10,-10,0};};
					class Unit5 	{side = TEast; vehicle = O_G_Soldier_F; rank = "PRIVATE"; position[] = {15,-15,0};};
					class Unit6 	{side = TEast; vehicle = O_G_Soldier_exp_F; rank = "PRIVATE"; position[] = {15,-20,0};}; //DO NOT EDIT : AA
				};
			};
		};
	};



};
