// config.bin - 18:32:50 07/16/20, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class A3_LanguageMissions_F_Beta {
		author = "$STR_A3_Bohemia_Interactive";
		name = "Arma 3 Beta - Mission Texts and Translations";
		url = "https://www.arma3.com";
		requiredAddons[] = {"A3_LanguageMissions_F"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {};
	};
};
